name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main  # 在 main 分支上进行推送时触发 
  schedule:
    - cron: '00 16 * * *'  # 每天凌晨 12 点执行

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Log the start time
        run: echo "Job started at $(date -u)"

      - name: Checkout repository
        uses: actions/checkout@v3
        run: echo "Checkout completed at $(date -u)"

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'
        run: echo "Python environment setup completed at $(date -u)"

      - name: install
        run: |
          pip install requests curl_cffi
          echo "Install completed at $(date -u)"

      - name: run
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Script started at $(date -u)"
          python nodeseek_sign.py
          echo "Script completed at $(date -u)"
